name: UIFactory
main: com.taylorswiftcn.megumi.uifactory.Main
version: ${project.version}
author: 'Megumi'
api-version: '1.13'
depend:
  - DragonCore

commands:
  uif:
    description: show all command